server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Medbeji/spring-cloud-config
      overrideSystemProperties: false
      overrideNone: true